### ISSUE TITLE
Codificación Arduino

### ISSUE THREAD

**Issue by VladP93** [MYE2020-A2-GRUPO-04/Archivos-Boveda_de_seguridad#3]
### Todo el código fuente de la placa Arduino requerido.

- [x] Codificar el uso de sensor dactilar

- [x] Programar uso de matriz de botones

- [x] Codificar uso de display

- [x] Codificar uso HC06

- [x] Codificar modulo de voz

- [x] Configurar 2FA con acceso y validaciones
